name:                zaphod
version:             0.1.0.0
github:              "farrellm/zaphod"
license:             BSD3
author:              "Matthew Farrell"
maintainer:          "farrellm@alum.mit.edu"
copyright:           "2019 Matthew Farrell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/farrellm/zaphod#readme>

default-extensions:
- ConstraintKinds
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections

dependencies:
- name: base
  version: ">= 4.7 && < 5"
  mixin:
    - hiding (Prelude)
- containers
- haskeline
- microlens-platform
- microlens
- megaparsec
- mtl
- optparse-applicative
- parser-combinators
- prettyprinter
- relude
- text

library:
  source-dirs: src

executables:
  zaphod:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zaphod

tests:
  zaphod-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zaphod
